### PR TITLE
lsstdesc_macros test/demo & cleanup

### PR DESCRIPTION
**Pull request by abmantz**
1. Implements a test that shows what each of our latex macros compiles to
2. Fixes(?) a couple of macros that caused problems
3. Cleans up the HTML bibliography part of the test Makefile

### CODE REVIEW

**Comment by kadrlica** [comment]
Tried to run `make -C test` locally on my Mac and hit this:

**Comment by abmantz** [comment]
And yet, surprisingly, Travis is fine with it. Do you have some kind of crazy non-GNU awk?

**Comment by kadrlica** [comment]
```awk -version
awk version 20070501

**Comment by kadrlica** [comment]
Sorry if I'm missing it, but aren't you [only testing on Linux](https://github.com/LSSTDESC/desc-tex/blob/70779c758b2a947bce17d6708f3306158935ae68/.travis.yml#L3-L4)?

**Comment by abmantz** [comment]
No, I'm testing on my mac. Then Travis does whatever it does, just to be as annoying as possible.

**Comment by abmantz** [comment]
Have you tried explicitly calling gawk rather than awk in the Makefile? It's hard to imagine what else could be going on.

**Comment by kadrlica** [comment]
```
> gawk
-bash: gawk: command not found
```

**Comment by kadrlica** [comment]
You can ask Travis to run mac checks too:
https://docs.travis-ci.com/user/reference/osx/

**Comment by abmantz** [comment]
It looks like the `match` command as used requires gawk. This is the key line that extracts the name and number of arguments of each macro. It could be coded otherwise in probably ~10 lines, but I'm not in a hurry to do so.

**Pull request merged**
