### PR TITLE
Note style: bigger margins, numbered sections

### PR DESCRIPTION
**Pull request by drphilmarshall**
I think these are valuable additions, but this is not ready to merge yet: the section numbers font, size and weight needs to match the section text. I'm not sure how to do that, everything I've tried so far has failed... Maybe you can see how to do it, @kadrlica ?

### CODE REVIEW

**Comment by kadrlica** [comment]
Do you have a screenshot of what you want? (I'll warn that I am not much of a fan of wider margins.)

**Comment by drphilmarshall** [comment]
Cracked it - I just hadn't spotted two small `\rm` commands in the section tex. OK, I think this is ready for review. An example output is [this PDF note](https://github.com/LSSTDESC/SLRealizer/blob/issue/17/desc-note/doc/slrealizer-concept-note/main.pdf)

**Comment by drphilmarshall** [comment]
Thanks Adam!

**Comment by kadrlica** [comment]
Thanks Adam (sorry, a bit busy the last few days).

**Pull request merged**
