### PR TITLE
Added first 2 DESC papers

### PR DESCRIPTION
**Pull request by drphilmarshall**
Straight from ADS.

### CODE REVIEW

**Comment by abmantz** [comment]
Can we think for a second before "straight from ADS" becomes the norm? There's a preprint in this addition, which is going to eventually be updated to an accepted paper. At that point we either need to abandon the "paste from ADS" paradigm anyway, or we'll be changing the key for the paper, which could break things for other people. So, before jumping into this, can I suggest we either
1. not add papers here until they have real journal references, or
2. assign everything a unique key according to our own convention (e.g. AuthorARXV.NUMBR) that stays the same after the entry is updated

**Comment by sethdigel** [comment]
The page in question is http://lsst-desc.org/node/47, which needs to be considered a stop gap until the Pub Management system can do this (on a different site).  The format of Phil's page is very nice I think.  The 'straight from ADS' meant I think that we are not attempting to host copies of the papers or preprints, which seems like the right approach to me.  I'm belatedly not sure what Adam mean by a 'key for the paper' and how things could get broken.

In another collaboration we maintain a public page of papers here:
https://www-glast.stanford.edu/cgi-bin/pubpub
It is generated on the fly and is effectively self maintaining, in that the authors of individual papers add the bibliographic information to the Pub Board database, and our experience over the years is that people are in  general very motivated to do that.  The script shows whatever bibliographic information it has been given.  Something like this is what I'd imagined (without much imagination) for DESC and the Publication Management System.

**Comment by abmantz** [comment]
This is regarding a bib file included in desc-tex, not a public webpage. I don't believe it was ever intended to be a replacement for a webpage, just a more convenient way for DESC papers to cite one another. Maybe the pub system could take over the job of generating the bib file, but the question raised above re: maintaining continuity in bibkeys is independent of that.

**Comment by sethdigel** [comment]
> This is regarding a bib file included in desc-tex, not a public webpage.

Sorry, clearly it relates to the bib file.  Not sure how I though otherwise.  Yes, for the bib file we need to come up with static 'key' values.  Adam's proposal seems sensible to me, a combination of something fairly human readable (the first author name) and something guaranteed to be unique, the arXiv number.  Any chance that we will have publications without arXiv numbers?  Science or Nature are a bit squirrely I think about posting papers on the arXiv.

**Comment by abmantz** [comment]
The system I use myself employs the arxiv number if there is one, and any other unique identifier if not. Usually, that means the ADS key (but still prepended by the author name), which is a little cumbersome, but at least not too common. Occasionally it's a DOI or JSTOR key (for journals that ADS doesn't track).

This works pretty well for me, but I don't want to force it on everyone unless others agree that it's sensible. It sounds like in steady state we will be relying on people to PR their papers into this file (maybe not, but that's how I interpreted your earlier comment), so as long as we can write down a finite and understandable convention it should be fine.

**Comment by sethdigel** [comment]
That sounds reasonable to me, Adam.  The only alternative that I can think of would be to use DESC-### numbers.  I'd personally find that aggravating, though.

I was imagining that in steady state, authors will add bibliographic information for their papers in the Publication Management system and a script will emit a DESC bibliography file on command.

**Comment by abmantz** [comment]
That would also work; we would just need to include the logic for assigning these keys in the pub management system. We should think about how we want the bib to be updated in the interim, i.e. whether it's the PB's job or the authors' job to submit a pull request. But all of that is independent of this PR.

I guess if there are no objections, I can modify the pull request consistent with the discussion above.

**Comment by abmantz** [comment]
I'm interpreting silence as tacit approval.

**Pull request merged**
